spring:
  application:
    name: hrm-user-keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:${keycloak.port}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

keycloak:
  url: http://localhost:${keycloak.port}/admin/realms
  port: 8282
  realm: hrm-realm
  client-id: spring-boot-rest-api
  id-client: a67c0cf1-d719-4dce-b7fb-a7337a205d8b
  token-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/token
  realm-uri: ${keycloak.url}/${keycloak.realm}